### ISSUE TITLE
Ignore specific page or files (.pdf, .json)

### ISSUE THREAD

**Issue by qdequele** [meilisearch/scrapix#1]
- [ ] Add the possibility to ignore pages or globs given by the user. 
- [x] Ignore pages that are files. 

It's possible to ignore pages with the [transform request](https://crawlee.dev/docs/introduction/adding-urls#transform-requests) method.

**Comment by bidoubiwa** [comment]
Can I close this?

**Comment by qdequele** [comment]
Yes
