### ISSUE TITLE
Create a scraper following schema.org

### ISSUE THREAD

**Issue by qdequele** [meilisearch/scrapix#12]
Create a new mode of scraper that will try to find schema.org json into the pages. 

The goal is to try to get the element with the selector `script[type='application/ld+json']` and parse the content in JSON. 

We can add two new parameters to the crawling request dedicated to schema crawling. 
- `schema_config.only_type` may allow the user to choose to only index pages that have a specific type (Product, Article...)
- `schema_config.convert_dates` would ask to convert the ISO dates into timestamps for a future ranking or sorting function into Meilisearch.

**Comment by bidoubiwa** [comment]
Can I close this one @qdequele ?

**Comment by qdequele** [comment]
yes 👍
