### ISSUE TITLE
Create script to zip and upload scrapix to AWS

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/scrapix#67]
⚠️ Issue needs to be moved

Currently, to update the lambda function it is required to manually zip the 
- AWS lambda function 
- The chromium binary
- The node_modules

When they are zipped, they need to be manually updated on the AWS console.

To avoid this complication, we need to create a script that zip and updates them automatically.

**Comment by brunoocasali** [comment]
Done!
